name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch: # Allows you to manually run the workflow

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # This action pushes to the branch for you.
          # We just need to tell it which branch to use.
          target_branch: output
        env:
          # The action needs this token to get permission to push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # The "mkdir", "mv", and "crazy-max/ghaction-github-pages" steps
      # are no longer needed because the action above does it all.

